### ISSUE TITLE
httpx.RemoteProtocolError not retry correctly

### ISSUE THREAD

**Issue by SysuJayce** [hynek/stamina#55] opened 2024-01-05 02:49 UTC
Hi there,
  I use `stamina` to retry my async function with `httpx.AsyncClient`, but once the request received `httpx.RemoteProtocolError`, the program died without retry.

Here is how I use `stamina`:
```
@stamina.retry(on=Exception, attempts=3, timeout=30)
async def func(url: str, params: dict, client: httpx.AsyncClient):
    response: httpx.Response = await client.post(url, json=params)
    response.raise_for_status()
```

Sorry I can not give you a snippet code to reproduce the problem because it just happens almost in 1/100k. I think the problem is that the server drop the connection and httpx still use that connection to send request. If this is the situation, maybe retry will not solve the problem either.
stamina version: 23.3.0
httpx version: 0.26.0

Below is the traceback:
```
Traceback (most recent call last):
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpcore/_async/http11.py", line 226, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.   

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/cms-test/text/netease.py", line 187, in query_text_async_helper
    response: httpx.Response = await client.post(
                               ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_client.py", line 1877, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/opt/conda/envs/cms-test/lib/python3.12/contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "/opt/conda/envs/cms-test/lib/python3.12/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
```

**Comment by hynek** [comment] 2024-01-05 06:01
What makes you so sure it didn't retry? Can you reproduce it by simply raising that exception and see what stamina does with it?

**Comment by SysuJayce** [comment] 2024-01-05 06:47
> What makes you so sure it didn't retry? Can you reproduce it by simply raising that exception and see what stamina does with it?

If I raise the same exception, stamina will print `stamina.retry_scheduled` twice, which is the expected behavior.
But I didn't find the any `stamina.retry_scheduled` in the above traceback, so I thought stamina didn't retry the function.

Can you tell me how to debug this problem? @hynek

**Comment by hynek** [comment] 2024-01-14 12:03
I'm gonna close this now because I don't know what actions I should be taking from this. I'd like to point out once more tho that there's no _stamina_ in your traceback whatsoever.

**Closed by hynek** 2024-01-14 12:03 UTC
Labels: bug
